SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT S.SUBMISSION_DATE, (
    SELECT COUNT(DISTINCT S2.HACKER_ID) FROM SUBMISSIONS S2 
    WHERE S2.SUBMISSION_DATE = S.SUBMISSION_DATE AND (
        SELECT COUNT(DISTINCT S3.SUBMISSION_DATE) FROM SUBMISSIONS S3 
        WHERE S3.HACKER_ID = S2.HACKER_ID AND S3.SUBMISSION_DATE <= S.SUBMISSION_DATE
    ) = S.SUBMISSION_DATE - DATE '2016-03-01' + 1
), H.HACKER_ID, H.NAME
FROM SUBMISSIONS S 
JOIN HACKERS H ON S.HACKER_ID = H.HACKER_ID
JOIN (
    SELECT SUBMISSION_DATE, HACKER_ID, ROW_NUMBER() OVER(
        PARTITION BY SUBMISSION_DATE 
        ORDER BY COUNT(*) DESC, HACKER_ID
    ) RN 
    FROM SUBMISSIONS
    GROUP BY SUBMISSION_DATE, HACKER_ID
)T 
ON S.SUBMISSION_DATE = T.SUBMISSION_DATE AND S.HACKER_ID = T.HACKER_ID
WHERE T.RN = 1
GROUP BY S.SUBMISSION_DATE, H.HACKER_ID, H.NAME
ORDER BY S.SUBMISSION_DATE;
exit;
