SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT CASE
WHEN P IS NULL THEN N || ' ' || 'Root'
WHEN N NOT IN (SELECT P FROM BST WHERE P IS NOT NULL) THEN N || ' ' || 'Leaf'
ELSE N || ' ' || 'Inner'
END FROM BST
ORDER BY N;
exit;
