SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) FROM HACKERS H
JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(*) = (
    SELECT MAX(CT) FROM (
        SELECT COUNT(*) CT FROM CHALLENGES
        GROUP BY HACKER_ID
    )
)
OR COUNT(*) IN (
    SELECT CT FROM (
        SELECT COUNT(*) CT FROM CHALLENGES
        GROUP BY HACKER_ID
    )
    GROUP BY CT
    HAVING COUNT(*) = 1
)
ORDER BY COUNT(*) DESC, H.HACKER_ID;
exit;
