SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT H.HACKER_ID, H.NAME, SUM(T.MAX_SCORE) AS TOTAL_SCORE FROM HACKERS H 
JOIN (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS MAX_SCORE FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) T
ON H.HACKER_ID = T.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(T.MAX_SCORE) > 0
ORDER BY SUM(T.MAX_SCORE) DESC, H.HACKER_ID;
exit;
