SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT RPAD('* ', LEVEL*2, '* ') FROM DUAL
CONNECT BY LEVEL <= 20;
exit;
