SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT C.CONTEST_ID, C.HACKER_ID, C.NAME, SUM(NVL(SS.TOTAL_SUBMISSIONS,0)), SUM(NVL(SS.TOTAL_ACCEPTED_SUBMISSIONS,0)), SUM(NVL(VS.TOTAL_VIEWS,0)), SUM(NVL(VS.TOTAL_UNIQUE_VIEWS,0)) FROM CONTESTS C 
JOIN COLLEGES CO ON C.CONTEST_ID = CO.CONTEST_ID
JOIN CHALLENGES CH ON CO.COLLEGE_ID = CH.COLLEGE_ID
LEFT JOIN (
    SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) TOTAL_SUBMISSIONS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) TOTAL_ACCEPTED_SUBMISSIONS
    FROM SUBMISSION_STATS 
    GROUP BY CHALLENGE_ID
)SS 
ON CH.CHALLENGE_ID = SS.CHALLENGE_ID
LEFT JOIN (
    SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) TOTAL_VIEWS, SUM(TOTAL_UNIQUE_VIEWS) TOTAL_UNIQUE_VIEWS
    FROM VIEW_STATS
    GROUP BY CHALLENGE_ID
)VS 
ON CH.CHALLENGE_ID = VS.CHALLENGE_ID
GROUP BY C.CONTEST_ID, C.HACKER_ID, C.NAME
HAVING SUM(NVL(SS.TOTAL_SUBMISSIONS,0)) + SUM(NVL(SS.TOTAL_ACCEPTED_SUBMISSIONS,0)) + SUM(NVL(VS.TOTAL_VIEWS,0)) + SUM(NVL(VS.TOTAL_UNIQUE_VIEWS,0)) > 0
ORDER BY C.CONTEST_ID;
exit;
