SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT W.ID, WP.AGE, W.COINS_NEEDED, W.POWER FROM WANDS W 
JOIN WANDS_PROPERTY WP ON W.CODE = WP.CODE
WHERE WP.IS_EVIL = 0 AND W.COINS_NEEDED = (
    SELECT MIN(W2.COINS_NEEDED) FROM WANDS W2
    JOIN WANDS_PROPERTY WP2 ON W2.CODE = WP2.CODE
    WHERE WP2.IS_EVIL = 0 AND W2.POWER = W.POWER AND WP2.AGE = WP.AGE
)
ORDER BY W.POWER DESC, WP.AGE DESC;
exit;
