SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
WITH NUMBERS AS (
    SELECT LEVEL NUM FROM DUAL
    CONNECT BY LEVEL <= 1000
)
SELECT LISTAGG(NUM, '&') WITHIN GROUP (ORDER BY NUM) FROM NUMBERS N 
WHERE NOT EXISTS (
    SELECT 1 FROM NUMBERS D 
    WHERE D.NUM BETWEEN 2 AND SQRT(N.NUM) AND MOD(N.NUM,D.NUM) = 0
)
AND NUM > 1;
exit;
