SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT S.START_DATE, MIN(E.END_DATE) FROM (
    SELECT START_DATE FROM PROJECTS
    WHERE START_DATE NOT IN (
        SELECT END_DATE FROM PROJECTS
    )
)S 
JOIN (
    SELECT END_DATE FROM PROJECTS
    WHERE END_DATE NOT IN (
        SELECT START_DATE FROM PROJECTS
    )
)E 
ON END_DATE > S.START_DATE 
GROUP BY S.START_DATE
ORDER BY MIN(E.END_DATE) - S.START_DATE, S.START_DATE;
exit;
