SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT CASE
WHEN G.GRADE >= 8 THEN S.NAME
ELSE NULL
END,
G.GRADE,S.MARKS
FROM STUDENTS S 
JOIN GRADES G ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK 
ORDER BY G.GRADE DESC,
CASE
WHEN G.GRADE >= 8 THEN S.NAME
END ASC,
CASE WHEN G.GRADE < 8 THEN S.MARKS
END ASC;
exit;
