SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT H.HACKER_ID, H.NAME FROM HACKERS H
JOIN SUBMISSIONS S ON H.HACKER_ID = S.HACKER_ID
JOIN CHALLENGES C ON S.CHALLENGE_ID = C.CHALLENGE_ID
JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(DISTINCT S.CHALLENGE_ID) > 1
ORDER BY COUNT(DISTINCT S.CHALLENGE_ID) DESC, H.HACKER_ID;
exit;
