SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT MAX(SALARY*MONTHS), COUNT(*) FROM EMPLOYEE
WHERE SALARY*MONTHS = (
    SELECT MAX(SALARY*MONTHS) FROM EMPLOYEE
);
exit;
