SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT CASE
WHEN A+B<=C OR B+C<=A OR A+C<=B THEN 'Not A Triangle'
WHEN A=B AND B=C THEN 'Equilateral'
WHEN A=B OR B=C OR A=C THEN 'Isosceles'
WHEN A!=B AND B!=C AND A!=C THEN 'Scalene' 
END 
FROM TRIANGLES;
exit;
