SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT DISTINCT CITY FROM STATION
WHERE SUBSTR(LOWER(CITY),1,1) NOT IN ('a','e','i','o','u')
OR SUBSTR(LOWER(CITY),-1,1) NOT IN ('a','e','i','o','u');
exit;
