SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT ROUND(SUM(LAT_N),4) FROM STATION
WHERE LAT_N>38.7880 AND LAT_N<137.2345;
exit;
