SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;
SELECT DISTINCT CITY FROM STATION
WHERE SUBSTR(LOWER(CITY),1,1) IN ('a', 'e', 'i', 'o', 'u')
AND SUBSTR(LOWER(CITY), -1, 1) IN ('a', 'e', 'i', 'o', 'u');
exit;
