SET NULL "NULL";
SET FEEDBACK OFF;
SET ECHO OFF;
SET HEADING OFF;
SET WRAP OFF;
SET LINESIZE 10000;
SET TAB OFF;
SET PAGES 0;
SET DEFINE OFF;

/*
Enter your query here.
Please append a semicolon ";" at the end of the query and enter your query in a single line to avoid error.
*/

SELECT CITY,LENGTH(CITY) FROM (
    SELECT CITY, LENGTH(CITY) FROM STATION
    ORDER BY LENGTH(CITY),CITY
)
WHERE ROWNUM = 1
UNION
SELECT CITY,LENGTH(CITY) FROM (
    SELECT CITY, LENGTH(CITY) FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY
)
WHERE ROWNUM = 1;
exit;
